#!/usr/bin/env python3
"""doctor.py — read-only memoir project health checks.

Exits 0 when no errors are found, 2 when any check errors. Warnings alone
do not fail. Use --json for machine-readable output.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import yaml

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

from build_memoir_api import (
    CACHE_DIRNAME,
    MANIFEST_FILENAME,
    MEMOIRS_DIR,
    PERIODS_DIR,
    TimelineParseError,
    build_event_ref,
    parse_timeline,
)
from time_spec import parse_time_spec
from workflow_guard import collect_unsynthesized_entries, is_draft_pending

WEBAPP_DIR = os.path.join(MEMOIRS_DIR, "webapp")
DIST_DIR = os.path.join(WEBAPP_DIR, "dist")
PUBLIC_DIR = os.path.join(WEBAPP_DIR, "public")
CACHE_MANIFEST = os.path.join(MEMOIRS_DIR, CACHE_DIRNAME, MANIFEST_FILENAME)

LEVEL_ORDER = {"error": 0, "warn": 1, "info": 2}


def check(level, code, message, **details):
    entry = {"level": level, "code": code, "message": message}
    if details:
        entry["details"] = details
    return entry


def list_periods():
    if not os.path.isdir(PERIODS_DIR):
        return []
    return sorted(
        name for name in os.listdir(PERIODS_DIR) if os.path.isdir(os.path.join(PERIODS_DIR, name))
    )


def read_timeline(period):
    timeline_path = os.path.join(PERIODS_DIR, period, "timeline.yaml")
    if not os.path.exists(timeline_path):
        return None, None
    with open(timeline_path, "r", encoding="utf-8") as file:
        try:
            return parse_timeline(file.read(), timeline_path), None
        except TimelineParseError as error:
            return None, str(error)


def legacy_data_paths():
    paths = [
        os.path.join(PUBLIC_DIR, MANIFEST_FILENAME),
        os.path.join(PUBLIC_DIR, "chapters"),
        os.path.join(PUBLIC_DIR, "assets"),
        os.path.join(DIST_DIR, MANIFEST_FILENAME),
        os.path.join(DIST_DIR, "memoirs.json"),
        os.path.join(DIST_DIR, "chapters"),
    ]
    for period in list_periods():
        paths.append(os.path.join(DIST_DIR, "assets", period))
    return [path for path in paths if os.path.exists(path)]


def check_layout(checks):
    legacy = legacy_data_paths()
    if legacy:
        checks.append(
            check(
                "error",
                "legacy_layout",
                "duplicated legacy data found under webapp/public or webapp/dist; run `memoir update` to migrate",
                paths=[os.path.relpath(path, MEMOIRS_DIR) for path in legacy],
            )
        )

    if not os.path.exists(CACHE_MANIFEST):
        checks.append(
            check("info", "manifest_missing", "no .cache manifest yet; it is generated by memoir build / memoir open")
        )
        return

    newest = 0.0
    for period in list_periods():
        for root_dir, _dirs, files in os.walk(os.path.join(PERIODS_DIR, period)):
            for name in files:
                if name.lower().endswith((".md", ".yaml", ".yml")):
                    newest = max(newest, os.path.getmtime(os.path.join(root_dir, name)))
    if newest > os.path.getmtime(CACHE_MANIFEST):
        checks.append(
            check("warn", "manifest_stale", "source data is newer than the .cache manifest; run memoir build or memoir open")
        )


def check_timelines(checks):
    for period in list_periods():
        timeline, error = read_timeline(period)
        if error:
            checks.append(check("error", "timeline_parse", error))
            continue
        if timeline is None:
            checks.append(check("warn", "missing_timeline", f"{period}: timeline.yaml not found"))
            continue

        refs: dict[str, int] = {}
        for entry in timeline.get("entries", []):
            if not isinstance(entry, dict):
                continue
            event = str(entry.get("event", "")).strip()
            if not event:
                checks.append(check("warn", "empty_event", f"{period}: timeline entry without an event title"))
                continue
            if not str(entry.get("id", "")).strip():
                checks.append(
                    check(
                        "warn",
                        "missing_id",
                        f"{period}: '{event}' has no stable id; run migrate_timeline_ids.py or memoir update",
                    )
                )
            ref = build_event_ref(period, entry)
            refs[ref] = refs.get(ref, 0) + 1
            date_text = str(entry.get("date", "")).strip()
            if date_text and parse_time_spec(date_text).status != "resolved":
                checks.append(
                    check("warn", "unresolved_time", f"{period}: '{event}' date '{date_text}' could not be normalized")
                )

        for ref in sorted(ref for ref, count in refs.items() if count > 1):
            checks.append(check("error", "duplicate_event_ref", f"{period}: duplicate event reference {ref}"))


def load_registry():
    """Load memoirs/entities.yaml from the project being examined."""
    registry_path = os.path.join(MEMOIRS_DIR, "entities.yaml")
    if not os.path.exists(registry_path):
        return {"people": {}, "places": {}}
    with open(registry_path, "r", encoding="utf-8") as file:
        try:
            data = yaml.safe_load(file) or {}
        except yaml.YAMLError as error:
            raise ValueError(f"Malformed YAML in {registry_path}: {error}") from error
    if not isinstance(data, dict):
        return {"people": {}, "places": {}}
    people = data.get("people") or {}
    places = data.get("places") or {}
    return {
        "people": people if isinstance(people, dict) else {},
        "places": places if isinstance(places, dict) else {},
    }


def check_places(checks):
    try:
        registry = load_registry()
    except ValueError as error:
        checks.append(check("error", "registry_parse", str(error)))
        return

    parents: dict[str, str] = {}
    for canonical, raw_meta in (registry.get("places") or {}).items():
        canonical_text = str(canonical)
        parent = str((raw_meta or {}).get("parent") or "").strip()
        if not parent and "·" in canonical_text:
            checks.append(
                check(
                    "warn",
                    "place_parent_inferred",
                    f"place '{canonical_text}' has no parent field; the FQN parent will be inferred",
                )
            )
            parent = canonical_text.split("·", 1)[0]
        if parent:
            parents[canonical_text] = parent

    for start in parents:
        seen: set[str] = set()
        current = start
        while current and current not in seen:
            seen.add(current)
            current = parents.get(current)
        if current:
            checks.append(check("error", "place_cycle", f"place parent cycle detected around '{current}'"))


def check_raw_notes(checks):
    for period in list_periods():
        timeline, error = read_timeline(period)
        if error or timeline is None:
            continue
        raw_dir = os.path.join(PERIODS_DIR, period, "raw_notes")
        for entry in timeline.get("entries", []):
            if not isinstance(entry, dict):
                continue
            for related in entry.get("related_files", []) or []:
                name = os.path.basename(str(related))
                if not os.path.exists(os.path.join(raw_dir, name)):
                    checks.append(
                        check(
                            "warn",
                            "missing_raw_note",
                            f"{period}: raw note missing for '{entry.get('event', '')}': {name}",
                        )
                    )


def check_chapters(checks):
    for item in collect_unsynthesized_entries():
        checks.append(
            check(
                "warn",
                "unsynthesized_entry",
                f"{item['period']}: '{item['event']}' ({item['date']}) has no chapter yet",
            )
        )


def check_draft(checks):
    if is_draft_pending():
        checks.append(check("warn", "draft_pending", "memoirs/.draft_buffer.md has uncommitted content; run /commit"))


def safe_check(function, checks):
    """Run one check; a crash is reported as an error instead of killing doctor."""
    try:
        function(checks)
    except Exception as error:  # noqa: BLE001 - doctor must always produce a report
        checks.append(check("error", "check_crashed", f"{function.__name__} crashed: {error}"))


def run_checks():
    checks = []
    if not os.path.isdir(PERIODS_DIR):
        checks.append(check("error", "periods_missing", f"periods dir not found: {PERIODS_DIR}"))
        return checks
    for function in (check_layout, check_timelines, check_places, check_raw_notes, check_chapters, check_draft):
        safe_check(function, checks)
    return checks


def summarize(checks):
    return {
        "errors": sum(1 for item in checks if item["level"] == "error"),
        "warnings": sum(1 for item in checks if item["level"] == "warn"),
        "infos": sum(1 for item in checks if item["level"] == "info"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Memoir project health checks (read-only).")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON")
    args = parser.parse_args()

    checks = run_checks()
    summary = summarize(checks)

    if args.json:
        print(json.dumps({"summary": summary, "checks": checks}, ensure_ascii=False, indent=2))
    else:
        if not checks:
            print("OK: memoir project looks healthy")
        for item in sorted(checks, key=lambda entry: LEVEL_ORDER.get(entry["level"], 9)):
            print(f"[{item['level']}] ({item['code']}) {item['message']}")
        print(
            f"\n{summary['errors']} error(s), {summary['warnings']} warning(s), {summary['infos']} info"
        )

    return 2 if summary["errors"] else 0


if __name__ == "__main__":
    sys.exit(main())
